env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 
  - 'eslint:recommended'
  - 'plugin:jsdoc/recommended'
  - 'standard'
globals:
  Atomics: 'readonly'
  SharedArrayBuffer: 'readonly'
parserOptions:
  ecmaVersion: 2018
rules: 
  jsdoc/require-jsdoc: 0
  jsdoc/check-tag-names: 0
settings:
  jsdoc:
    mode: 'typescript'
plugins:
  - 'jsdoc'
