env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 
  - 'eslint:recommended'
  - 'plugin:jsdoc/recommended'
globals:
  Atomics: 'readonly'
  SharedArrayBuffer: 'readonly'
parserOptions:
  ecmaVersion: 2018
rules: 
  editorconfig/editorconfig: "error"
  jsdoc/require-jsdoc: 0
  jsdoc/check-tag-names: 0
  semi: [warn, never]
  quotes: [warn, single]
settings:
  jsdoc:
    mode: 'typescript'
plugins:
  - 'jsdoc'
  - 'editorconfig'
