env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 
  - 'eslint:recommended'
  - 'plugin:jsdoc/recommended'
globals:
  Atomics: 'readonly'
  SharedArrayBuffer: 'readonly'
parserOptions:
  ecmaVersion: 2018
rules: {}
settings:
  jsdoc:
    mode: 'typescript'
plugins:
  - 'jsdoc'